[package]
authors = ["Osspial <osspial@gmail.com>"]
name = "derin"
version = "0.1.0"

[dependencies]
rand = "0.3"
boolinator = "2.0"
lazy_static = "0.2"
smallvec = "0.2"

winapi = "0.2"
user32-sys = "0.1"
kernel32-sys = "0.2"
dwmapi-sys = "0.1"
