[package]
authors = ["Osspial <osspial@gmail.com>"]
name = "derin"
version = "0.1.0"

[dependencies]
dle = {path = "./dle"}
dct = {path = "./dct"}
dww = {path = "./dww"}
dww_macros = {path = "./dww_macros"}
lazy_static = "0.2"

[dev-dependencies]
quickcheck = "0.4"
derin_macros = {path = "./derin_macros"}

[workspace]
members = ["./dct", "./dle", "./dww", "./dww_macros", "./derin_macros"]
