[package]
authors = ["Osspial <osspial@gmail.com>"]
name = "derin"
version = "0.1.0"

[dependencies]
rand = "0.3"
dle = {path = "./dle"}
dct = {path = "./dct"}
dww = {path = "./dww"}
dww_macros = {path = "./dww_macros"}

[dev-dependencies]
quickcheck = "0.4"

[workspace]
members = ["./dct", "./dle", "./dww", "./dww_macros"]
