[package]
authors = ["Osspial <osspial@gmail.com>"]
name = "derin"
version = "0.1.0"

[dependencies]
rand = "0.3"
boolinator = "2.0"
lazy_static = "0.2"
smallvec = "0.2"
dle = {path = "./dle"}
dct = {path = "./dct"}
dww = {path = "./dww"}
dww_macros = {path = "./dww_macros"}

winapi = "0.2"
user32-sys = "0.1"
kernel32-sys = "0.2"
dwmapi-sys = "0.1"
comctl32-sys = "0.2"

[dev-dependencies]
quickcheck = "0.4"

[workspace]
members = ["./dct", "./dle", "./dww", "./dww_macros"]
