[package]
authors = ["Osspial <osspial@gmail.com>"]
name = "tint"
version = "0.1.0"

[dependencies]
bitflags = "0.7.0"
fnv = "1.0"
winapi = "0.2"
user32-sys = "0.1"
kernel32-sys = "0.2"
dwmapi-sys = "0.1"

cgmath = { version = "0.12", optional = true}
freetype-rs = { version = "0.11", optional = true}
gl = { version = "0.6", optional = true}
glutin = { version = "0.6", optional = true}

[features]
gl_ui = ["gl", "gl_raii", "glutin", "freetype-rs", "cgmath"]

[dependencies.gl_raii]
path = "./gl_raii"
optional = true

[workspace]
members = ["./gl_raii"]
