[package]
name = "tint"
version = "0.1.0"
authors = ["Osspial <osspial@gmail.com>"]

[dependencies]
gl = "0.6"
gl_raii = {path="./gl_raii"}
cgmath = "0.11"
freetype-rs = "0.11"

[dev-dependencies]
glutin = "0.6"

[workspace]
members = ["./gl_raii"]
