[package]
name = "dat"
version = "0.1.0"
authors = ["Osspial <osspial@gmail.com>"]

[dependencies]
cgmath = {git = "https://github.com/Osspial/cgmath.git", branch = "prs_merged"}
cgmath-geometry = { git = "https://github.com/Osspial/cgmath-geometry.git" }

[dev-dependencies]
image = "0.16"
