[package]
name = "dct"
version = "0.1.0"
authors = ["Osspial <osspial@gmail.com>"]
license = "Apache-2.0"

[dependencies]
num-traits = "0.1"
cgmath-geometry = { git = "https://github.com/Osspial/cgmath-geometry.git" }
bitflags = "1.0"
