[package]
name = "dct"
version = "0.1.0"
authors = ["Osspial <osspial@gmail.com>"]

[dependencies]
cgmath = "0.15"
num-traits = "0.1"
cgmath-geometry = { git = "https://github.com/Osspial/cgmath-geometry.git" }
