[package]
name = "derin_core"
version = "0.1.0"
authors = ["Osspial <osspial@gmail.com>"]

[dependencies]
bitflags = "1.0"
cgmath-geometry = { git = "https://github.com/Osspial/cgmath-geometry.git" }
dct = { path = "../dct" }
arrayvec = "0.4"
itertools = "0.7"
