[package]
name = "derin_core"
version = "0.1.0"
authors = ["Osspial <osspial@gmail.com>"]

[dependencies]
cgmath = { git = "https://github.com/Osspial/cgmath.git", branch = "prs_merged" }
dct = { path = "../dct" }
