[package]
name = "dww"
version = "0.1.0"
authors = ["Osspial <osspial@gmail.com>"]

[dependencies]
winapi = "0.2"
user32-sys = "0.1"
kernel32-sys = "0.2"
comctl32-sys = "0.2"
lazy_static = "0.2"
dct = {path = "../dct"}

[dev-dependencies.dww_macros]
path = "../dww_macros"
features = ["inside_dww"]
