[package]
name = "derin_macros"
edition = "2018"
version = "0.1.0"
authors = ["Osspial <osspial@gmail.com>"]
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = "0.11"
quote = "0.3"
