[package]
name = "derin_atlas"
version = "0.1.0"
authors = ["Osspial <osspial@gmail.com>"]
license = "Apache-2.0"

[dependencies]
cgmath-geometry = { git = "https://github.com/Osspial/cgmath-geometry.git" }

[dev-dependencies]
image = "0.16"
